# Generated by Django 6.0.4 on 2026-04-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0003_team_downstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
