# Generated by Django 6.0.4 on 2026-04-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
