# Generated by Django 6.0.4 on 2026-04-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0002_team_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='downstream',
            field=models.ManyToManyField(blank=True, related_name='upstream', to='teams_app.team'),
        ),
    ]
