# Generated by Django 4.2.30 on 2026-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0001_initial'),
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
        migrations.AddField(
            model_name='meeting',
            name='optional_attendees',
            field=models.ManyToManyField(blank=True, related_name='optional_meetings', to='teams_app.engineer'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='platform',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('in_person', 'In Person'), ('other', 'Other')], default='zoom', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='required_attendees',
            field=models.ManyToManyField(blank=True, related_name='required_meetings', to='teams_app.engineer'),
        ),
    ]
