# Generated by Django 6.0.4 on 2026-04-28 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(default=1, upload_to='reports/'),
            preserve_default=False,
        ),
    ]
