# Generated by Django 6.0.4 on 2026-04-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0003_report_created_at_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
    ]
